#!/bin/bash

DIR=`dirname $0`

tempDir=`mktemp -d`
mkfifo $tempDir/condition
mkfifo $tempDir/temperature

# We work with fds in order not to close the pipes
exec 4<>$tempDir/condition
%PREFIXDIR%/bin/trayIcon < $tempDir/condition &
pidCond=$!
exec 5<>$tempDir/temperature
%PREFIXDIR%/bin/trayIcon < $tempDir/temperature &
pidTemp=$!

function rmTempDir() {
    echo "Killing tray icons"
    kill $pidTemp $pidCond
    echo "Removing $tempDir"
    rm -rf $tempDir
    exit
}

trap "rmTempDir" 2

# The temperature icon will always be the same. We set it here and the we do reloads.
echo icon %PREFIXDIR%/share/trayIcon/weather/icons/unknown.png 1>&4
sleep 1 # This is done so the condition icon comes before the temperature icon
tempIcon=$tempDir/temperature.png
echo icon $tempIcon 1>&5

while true; do
    IFS="	" read temperature condition icon < <(python2 %PREFIXDIR%/lib/trayIcon/weather/weathercli.py 10245) 
    condition=$(echo $condition | tr -d '"')
    normCondition=$(echo $condition | tr ' ' '_')
    condition=$(echo $condition | sed -r 's/(.)/\u\1/')

    # Condition icon
    condIcon=%PREFIXDIR%/share/trayIcon/weather/icons/${normCondition}.png
    if [ -f $condIcon ]; then
        echo icon $condIcon
    else
        echo icon %PREFIXDIR%/share/trayIcon/weather/icons/unknown.png
        echo $condIcon >> $HOME/weather-missingIcons
    fi 1>&4
    echo tooltip $condition, $temperature° 1>&4

    # Temperature icon
    convert -size 16x16 -background none \
        -font /usr/share/texmf-dist/fonts/truetype/public/dejavu/DejaVuSerif.ttf \
        -fill white -pointsize 10 -gravity center label:"$temperature°" $tempIcon
    echo reload 1>&5
    echo tooltip $condition, $temperature° 1>&5

    sleep $((30*60))
done
